# configuration: production
spring:
   config:
      activate:
         on-profile: production

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.64.9:3307/webdb?charset=utf8
      username: webdb
      password: '{cipher}AYBCd4kOtuw5c+QBVMn/lbJOcnvI/vjPC7FtLjZQgtDLlvI73idJu2WQ0d+FqjVfXINHS6X6XRIqIR2oglch5uz9C9QX3lLTJMWvzgCMDMBtaYmaC5dIAOfx2ISLURpklNzQzliqjkGBlbhTUbOFKpkGb8S+gZkFd9l/Bjener8GEMZiV2eEJqL5x9SEWcSJG6XYF4FF/YL+VT28TZahuZPMbCtpYW3QDhE2nkuGT1xzeK5qTiP6nIlE8rxJXhwD1DK2MzPp5FgT1UF0FhB/nI8rr84UOBhQotM3RE21AkpFBxaWZYg7ZrtJxH4E3VKwevOCDBg5CkU5oIvkj1GIcl+lfvGVN+GusS5Ctqacs3PlunxyeREFq6TIdtdInvsT9mDuyxTBFUeg/dF8X035a57pkB5aaGNySy/Apd1k7q7jKRFvP9O83DB/yBc3qJgQckd89UYi9A+bAFPJWHrN7Z3w14uvjgSoqlR8sAAzCqQU5GQBkh7Wxo+5RqD6GPUbkS7/YWOiMWbkmtJnhXBUSwsc0GECy/kWPT2rHNCZHqzGNg=='
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: "logs/${spring.application.name}.%d{yyyy-MM-dd}.%i.log.zip"
         max-file-size: 10MB
         max-history: 10
   file:
      name: logs/${spring.application.name}.log
   level:
      root: WARN
      com:
         poscodx:
            msa:
               service:
                  guestbook:
                     exception: ERROR
                              
eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://192.168.64.9:8761/eureka